version: "3"

networks:
  mgs_mgs:
    external: true

services:
  mgs-core:
    build: .
    restart: always
    ports:
      - "5555:5555"
    networks:
      - mgs_mgs
    labels:
      co.elastic.logs/enable: "true"
      co.elastic.logs/multiline.pattern: '^\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}\.\d{3}\s'
      co.elastic.logs/multiline.negate: "true"
      co.elastic.logs/multiline.match: after
    logging:
      driver: "json-file"
    volumes:
      - /data/static/map:/data/static/map
      - ./models/:/root/mgs-core/src/qa/models/
