# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from src.rpc.proto import GPT_pb2 as src_dot_rpc_dot_proto_dot_GPT__pb2


class GPTServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAnswerWithGPT = channel.unary_unary(
                '/GPTService/GetAnswerWithGPT',
                request_serializer=src_dot_rpc_dot_proto_dot_GPT__pb2.GPTRequest.SerializeToString,
                response_deserializer=src_dot_rpc_dot_proto_dot_GPT__pb2.GPTReply.FromString,
                )


class GPTServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAnswerWithGPT(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GPTServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAnswerWithGPT': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAnswerWithGPT,
                    request_deserializer=src_dot_rpc_dot_proto_dot_GPT__pb2.GPTRequest.FromString,
                    response_serializer=src_dot_rpc_dot_proto_dot_GPT__pb2.GPTReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GPTService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GPTService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAnswerWithGPT(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GPTService/GetAnswerWithGPT',
            src_dot_rpc_dot_proto_dot_GPT__pb2.GPTRequest.SerializeToString,
            src_dot_rpc_dot_proto_dot_GPT__pb2.GPTReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
