# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/rpc/proto/GPT.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='src/rpc/proto/GPT.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17src/rpc/proto/GPT.proto\"\x88\x01\n\nGPTRequest\x12\x15\n\ruser_question\x18\x01 \x01(\t\x12\x15\n\rexhibit_label\x18\x02 \x01(\t\x12\x1b\n\x13\x65xhibit_description\x18\x03 \x01(\t\x12\x13\n\x0bmuseum_name\x18\x04 \x01(\t\x12\x1a\n\x12museum_description\x18\x05 \x01(\t\"`\n\x08GPTReply\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x12\n\ncompletion\x18\x02 \x01(\t\x12\x15\n\rprompt_tokens\x18\x03 \x01(\x05\x12\x19\n\x11\x63ompletion_tokens\x18\x04 \x01(\x05\x32:\n\nGPTService\x12,\n\x10GetAnswerWithGPT\x12\x0b.GPTRequest\x1a\t.GPTReply\"\x00\x62\x06proto3'
)




_GPTREQUEST = _descriptor.Descriptor(
  name='GPTRequest',
  full_name='GPTRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_question', full_name='GPTRequest.user_question', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='exhibit_label', full_name='GPTRequest.exhibit_label', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='exhibit_description', full_name='GPTRequest.exhibit_description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='museum_name', full_name='GPTRequest.museum_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='museum_description', full_name='GPTRequest.museum_description', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=164,
)


_GPTREPLY = _descriptor.Descriptor(
  name='GPTReply',
  full_name='GPTReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='prompt', full_name='GPTReply.prompt', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='completion', full_name='GPTReply.completion', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='prompt_tokens', full_name='GPTReply.prompt_tokens', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='completion_tokens', full_name='GPTReply.completion_tokens', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=166,
  serialized_end=262,
)

DESCRIPTOR.message_types_by_name['GPTRequest'] = _GPTREQUEST
DESCRIPTOR.message_types_by_name['GPTReply'] = _GPTREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GPTRequest = _reflection.GeneratedProtocolMessageType('GPTRequest', (_message.Message,), {
  'DESCRIPTOR' : _GPTREQUEST,
  '__module__' : 'src.rpc.proto.GPT_pb2'
  # @@protoc_insertion_point(class_scope:GPTRequest)
  })
_sym_db.RegisterMessage(GPTRequest)

GPTReply = _reflection.GeneratedProtocolMessageType('GPTReply', (_message.Message,), {
  'DESCRIPTOR' : _GPTREPLY,
  '__module__' : 'src.rpc.proto.GPT_pb2'
  # @@protoc_insertion_point(class_scope:GPTReply)
  })
_sym_db.RegisterMessage(GPTReply)



_GPTSERVICE = _descriptor.ServiceDescriptor(
  name='GPTService',
  full_name='GPTService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=264,
  serialized_end=322,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetAnswerWithGPT',
    full_name='GPTService.GetAnswerWithGPT',
    index=0,
    containing_service=None,
    input_type=_GPTREQUEST,
    output_type=_GPTREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GPTSERVICE)

DESCRIPTOR.services_by_name['GPTService'] = _GPTSERVICE

# @@protoc_insertion_point(module_scope)
