# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/rpc/proto/QA.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='src/rpc/proto/QA.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16src/rpc/proto/QA.proto\"*\n\x0eRpcExhibitText\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04text\x18\x02 \x01(\t\"M\n\tQARequest\x12\x10\n\x08question\x18\x01 \x01(\t\x12\x1e\n\x05texts\x18\x02 \x03(\x0b\x32\x0f.RpcExhibitText\x12\x0e\n\x06status\x18\x03 \x01(\x05\")\n\x18\x45xhibitLabelAliasRequest\x12\r\n\x05texts\x18\x01 \x03(\t\"@\n\x07QAReply\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\x12\x0f\n\x07text_id\x18\x02 \x01(\x03\x12\x14\n\x0c\x66rom_open_qa\x18\x03 \x01(\x08\")\n\x16\x45xhibitLabelAliasReply\x12\x0f\n\x07\x61liases\x18\x01 \x03(\t2\xa8\x01\n\tMyService\x12#\n\tGetAnswer\x12\n.QARequest\x1a\x08.QAReply\"\x00\x12-\n\x13GetAnswerWithOpenQA\x12\n.QARequest\x1a\x08.QAReply\"\x00\x12G\n\x0fGetExhibitAlias\x12\x19.ExhibitLabelAliasRequest\x1a\x17.ExhibitLabelAliasReply\"\x00\x62\x06proto3'
)




_RPCEXHIBITTEXT = _descriptor.Descriptor(
  name='RpcExhibitText',
  full_name='RpcExhibitText',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='RpcExhibitText.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='text', full_name='RpcExhibitText.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=68,
)


_QAREQUEST = _descriptor.Descriptor(
  name='QARequest',
  full_name='QARequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='question', full_name='QARequest.question', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='texts', full_name='QARequest.texts', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='QARequest.status', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=147,
)


_EXHIBITLABELALIASREQUEST = _descriptor.Descriptor(
  name='ExhibitLabelAliasRequest',
  full_name='ExhibitLabelAliasRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='texts', full_name='ExhibitLabelAliasRequest.texts', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=190,
)


_QAREPLY = _descriptor.Descriptor(
  name='QAReply',
  full_name='QAReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='answer', full_name='QAReply.answer', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='text_id', full_name='QAReply.text_id', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='from_open_qa', full_name='QAReply.from_open_qa', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=192,
  serialized_end=256,
)


_EXHIBITLABELALIASREPLY = _descriptor.Descriptor(
  name='ExhibitLabelAliasReply',
  full_name='ExhibitLabelAliasReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='aliases', full_name='ExhibitLabelAliasReply.aliases', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=258,
  serialized_end=299,
)

_QAREQUEST.fields_by_name['texts'].message_type = _RPCEXHIBITTEXT
DESCRIPTOR.message_types_by_name['RpcExhibitText'] = _RPCEXHIBITTEXT
DESCRIPTOR.message_types_by_name['QARequest'] = _QAREQUEST
DESCRIPTOR.message_types_by_name['ExhibitLabelAliasRequest'] = _EXHIBITLABELALIASREQUEST
DESCRIPTOR.message_types_by_name['QAReply'] = _QAREPLY
DESCRIPTOR.message_types_by_name['ExhibitLabelAliasReply'] = _EXHIBITLABELALIASREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RpcExhibitText = _reflection.GeneratedProtocolMessageType('RpcExhibitText', (_message.Message,), {
  'DESCRIPTOR' : _RPCEXHIBITTEXT,
  '__module__' : 'src.rpc.proto.QA_pb2'
  # @@protoc_insertion_point(class_scope:RpcExhibitText)
  })
_sym_db.RegisterMessage(RpcExhibitText)

QARequest = _reflection.GeneratedProtocolMessageType('QARequest', (_message.Message,), {
  'DESCRIPTOR' : _QAREQUEST,
  '__module__' : 'src.rpc.proto.QA_pb2'
  # @@protoc_insertion_point(class_scope:QARequest)
  })
_sym_db.RegisterMessage(QARequest)

ExhibitLabelAliasRequest = _reflection.GeneratedProtocolMessageType('ExhibitLabelAliasRequest', (_message.Message,), {
  'DESCRIPTOR' : _EXHIBITLABELALIASREQUEST,
  '__module__' : 'src.rpc.proto.QA_pb2'
  # @@protoc_insertion_point(class_scope:ExhibitLabelAliasRequest)
  })
_sym_db.RegisterMessage(ExhibitLabelAliasRequest)

QAReply = _reflection.GeneratedProtocolMessageType('QAReply', (_message.Message,), {
  'DESCRIPTOR' : _QAREPLY,
  '__module__' : 'src.rpc.proto.QA_pb2'
  # @@protoc_insertion_point(class_scope:QAReply)
  })
_sym_db.RegisterMessage(QAReply)

ExhibitLabelAliasReply = _reflection.GeneratedProtocolMessageType('ExhibitLabelAliasReply', (_message.Message,), {
  'DESCRIPTOR' : _EXHIBITLABELALIASREPLY,
  '__module__' : 'src.rpc.proto.QA_pb2'
  # @@protoc_insertion_point(class_scope:ExhibitLabelAliasReply)
  })
_sym_db.RegisterMessage(ExhibitLabelAliasReply)



_MYSERVICE = _descriptor.ServiceDescriptor(
  name='MyService',
  full_name='MyService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=302,
  serialized_end=470,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetAnswer',
    full_name='MyService.GetAnswer',
    index=0,
    containing_service=None,
    input_type=_QAREQUEST,
    output_type=_QAREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetAnswerWithOpenQA',
    full_name='MyService.GetAnswerWithOpenQA',
    index=1,
    containing_service=None,
    input_type=_QAREQUEST,
    output_type=_QAREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetExhibitAlias',
    full_name='MyService.GetExhibitAlias',
    index=2,
    containing_service=None,
    input_type=_EXHIBITLABELALIASREQUEST,
    output_type=_EXHIBITLABELALIASREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MYSERVICE)

DESCRIPTOR.services_by_name['MyService'] = _MYSERVICE

# @@protoc_insertion_point(module_scope)
